steps:
# REMOVE AFTER TESTING
# Run docker stats in the background.
# --no-stream is used in order to print the stats on different lines.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'run'
  - '-d'
  - '--name=docker-stats'
  - '--volume=/var/run/docker.sock:/var/run/docker.sock'
  - '--entrypoint=/bin/bash'
  - 'gcr.io/cloud-builders/docker'
  - '-c'
  - 'while true; do docker stats --no-stream; sleep 1; done'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --rm # we can probably remove
  - --no-cache # same
  - --tag=gcr.io/$PROJECT_ID/rcran-build:temp64
  - .

# TODO(philmod): keep for future debugging?
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - gcr.io/$PROJECT_ID/rcran-build:temp64

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    
    # Verify 'convert' (ImageMagick) is available.
    docker run --rm -t --read-only --net=none \
      gcr.io/$PROJECT_ID/rcran-build:temp64 \
      convert --version

    rm -rf /tmp/rcran-build
    mkdir -p /tmp/rcran-build/tmp
    mkdir -p /tmp/rcran-build/devshm
    mkdir -p /tmp/rcran-build/working
    docker run --rm -t --read-only --net=none \
      -e HOME=/tmp -v $$PWD:/input:ro \
      -v /tmp/rcran-build/working:/working \
      -w=/working \
      -v /tmp/rcran-build/tmp:/tmp \
      -v /tmp/rcran-build/devshm:/dev/shm \
      gcr.io/$PROJECT_ID/rcran-build:temp64 \
      /bin/bash -c 'Rscript /input/test_build.R'

    # Verify expected test_build.R output is present.
    [ -s /tmp/rcran-build/working/plot1.png ]

    echo "ok"

# images: ['gcr.io/kaggle-images/rcran']

options:
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: 1000 # does that give more IOPS?

timeout: 86400s