steps:

# Fetch packages used by users from BigQuery.
# The `bq` image has been built previously in the project:
# $ git clone https://github.com/GoogleCloudPlatform/cloud-builders-community.git
# $ cd cloud-builders-community/bq
# $ gcloud builds submit
- id: 'fetch-packages'
  name: 'gcr.io/$PROJECT_ID/bq'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -eo pipefail
    bq query \
    --use_legacy_sql=false \
    --format=sparse \
    'SELECT PackageName FROM `kaggle-infra-analytics.kaggle_derived.KernelBlobsRPackages`' \
    >&1 bq_response
    # Ignore tensorflow which is installed in docker-rstats image.
    # Also ignore the headers of the search results.
    cat bq_response | grep -v 'tensorflow' | awk 'NR>2' > packages_users

- id: 'build'
  waitFor: ['fetch-packages']
  name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --rm
  - --no-cache
  - --tag=gcr.io/$PROJECT_ID/rcran-build:$BUILD_ID
  - .

# Pushing the intermediate image can be useful to debug test failures.
- id: 'intermediate-push'
  waitFor: ['build']
  name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - gcr.io/$PROJECT_ID/rcran-build:$BUILD_ID

# Verify 'convert' (ImageMagick) is available.
- id: 'test-convert'
  waitFor: ['intermediate-push'] # Otherwise the test failure should stop push.
  name: 'gcr.io/$PROJECT_ID/rcran-build:$BUILD_ID'
  args: ['convert', '--version']

- id: 'test'
  waitFor: ['intermediate-push'] # Otherwise the test failure should stop push.
  name: 'gcr.io/$PROJECT_ID/rcran-build:$BUILD_ID'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e
    Rscript test_build.R
    # Verify expected test_build.R output is present.
    [ -s plot1.png ]
    echo "ok"

- id: 'retag'
  waitFor: ['test', 'test-convert']
  name: 'gcr.io/cloud-builders/docker'
  args:
  - tag
  - gcr.io/$PROJECT_ID/rcran-build:$BUILD_ID
  - gcr.io/kaggle-images/rcran:$_TAG

images: ['gcr.io/kaggle-images/rcran:$_TAG']

options:
  # Use of largest GCB instance size in shared pool.
  # Upon change, update Ncpus in package_installs.R.
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: 1000 # Max disk size. Gives more IOPS.

timeout: 86400s

substitutions:
  _TAG: testing # Change to latest for production.

tags: ['rcran']